server:
  port: 8080

logging:
  level:
    root: debug

spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: auth-server
        registration:
          gateway-client:
            provider: spring
            client-id: gateway
            client-secret: Gateway1!
            scope:
              - openid
            post_logout_url: ${POST_LOGOUT_URL}
  cloud:
    gateway:
      routes:
        - id: apple
          uri: https://apple.com
          predicates:
            - Path=/apple/**
          filters:
            - TokenRelay=
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}